package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/deicod/tarife/ent"
	"github.com/deicod/tarife/graph/generated"
	"github.com/rs/xid"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id xid.ID) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []xid.ID) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// Addons is the resolver for the addons field.
func (r *queryResolver) Addons(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.AddonWhereInput) (*ent.AddonConnection, error) {
	panic(fmt.Errorf("not implemented: Addons - addons"))
}

// Bandwidths is the resolver for the bandwidths field.
func (r *queryResolver) Bandwidths(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.BandwidthWhereInput) (*ent.BandwidthConnection, error) {
	panic(fmt.Errorf("not implemented: Bandwidths - bandwidths"))
}

// OneTimeFees is the resolver for the oneTimeFees field.
func (r *queryResolver) OneTimeFees(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.OneTimeFeeWhereInput) (*ent.OneTimeFeeConnection, error) {
	panic(fmt.Errorf("not implemented: OneTimeFees - oneTimeFees"))
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.PlanWhereInput) (*ent.PlanConnection, error) {
	panic(fmt.Errorf("not implemented: Plans - plans"))
}

// PriceTiers is the resolver for the priceTiers field.
func (r *queryResolver) PriceTiers(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.PriceTierWhereInput) (*ent.PriceTierConnection, error) {
	panic(fmt.Errorf("not implemented: PriceTiers - priceTiers"))
}

// Promos is the resolver for the promos field.
func (r *queryResolver) Promos(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.PromoWhereInput) (*ent.PromoConnection, error) {
	panic(fmt.Errorf("not implemented: Promos - promos"))
}

// Providers is the resolver for the providers field.
func (r *queryResolver) Providers(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.ProviderWhereInput) (*ent.ProviderConnection, error) {
	panic(fmt.Errorf("not implemented: Providers - providers"))
}

// Snapshots is the resolver for the snapshots field.
func (r *queryResolver) Snapshots(ctx context.Context, after *entgql.Cursor[xid.ID], first *int, before *entgql.Cursor[xid.ID], last *int, where *ent.SnapshotWhereInput) (*ent.SnapshotConnection, error) {
	panic(fmt.Errorf("not implemented: Snapshots - snapshots"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
