// Code generated by ent, DO NOT EDIT.

package addon

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the addon type in the database.
	Label = "addon"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMonthlyFeeCents holds the string denoting the monthly_fee_cents field in the database.
	FieldMonthlyFeeCents = "monthly_fee_cents"
	// EdgePlans holds the string denoting the plans edge name in mutations.
	EdgePlans = "plans"
	// Table holds the table name of the addon in the database.
	Table = "addons"
	// PlansTable is the table that holds the plans relation/edge. The primary key declared below.
	PlansTable = "addon_plans"
	// PlansInverseTable is the table name for the Plan entity.
	// It exists in this package in order to avoid circular dependency with the "plan" package.
	PlansInverseTable = "plans"
)

// Columns holds all SQL columns for addon fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldMonthlyFeeCents,
}

var (
	// PlansPrimaryKey and PlansColumn2 are the table columns denoting the
	// primary key for the plans relation (M2M).
	PlansPrimaryKey = []string{"addon_id", "plan_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// OrderOption defines the ordering options for the Addon queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMonthlyFeeCents orders the results by the monthly_fee_cents field.
func ByMonthlyFeeCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyFeeCents, opts...).ToFunc()
}

// ByPlansCount orders the results by plans count.
func ByPlansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlansStep(), opts...)
	}
}

// ByPlans orders the results by plans terms.
func ByPlans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PlansTable, PlansPrimaryKey...),
	)
}
