// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/tarife/ent/addon"
	"github.com/rs/xid"
)

// Addon is the model entity for the Addon schema.
type Addon struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MonthlyFeeCents holds the value of the "monthly_fee_cents" field.
	MonthlyFeeCents int `json:"monthly_fee_cents,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AddonQuery when eager-loading is set.
	Edges        AddonEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AddonEdges holds the relations/edges for other nodes in the graph.
type AddonEdges struct {
	// Plans holds the value of the plans edge.
	Plans []*Plan `json:"plans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedPlans map[string][]*Plan
}

// PlansOrErr returns the Plans value or an error if the edge
// was not loaded in eager-loading.
func (e AddonEdges) PlansOrErr() ([]*Plan, error) {
	if e.loadedTypes[0] {
		return e.Plans, nil
	}
	return nil, &NotLoadedError{edge: "plans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Addon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case addon.FieldMonthlyFeeCents:
			values[i] = new(sql.NullInt64)
		case addon.FieldName:
			values[i] = new(sql.NullString)
		case addon.FieldID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Addon fields.
func (_m *Addon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case addon.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case addon.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case addon.FieldMonthlyFeeCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_fee_cents", values[i])
			} else if value.Valid {
				_m.MonthlyFeeCents = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Addon.
// This includes values selected through modifiers, order, etc.
func (_m *Addon) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlans queries the "plans" edge of the Addon entity.
func (_m *Addon) QueryPlans() *PlanQuery {
	return NewAddonClient(_m.config).QueryPlans(_m)
}

// Update returns a builder for updating this Addon.
// Note that you need to call Addon.Unwrap() before calling this method if this Addon
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Addon) Update() *AddonUpdateOne {
	return NewAddonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Addon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Addon) Unwrap() *Addon {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Addon is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Addon) String() string {
	var builder strings.Builder
	builder.WriteString("Addon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("monthly_fee_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyFeeCents))
	builder.WriteByte(')')
	return builder.String()
}

// NamedPlans returns the Plans named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Addon) NamedPlans(name string) ([]*Plan, error) {
	if _m.Edges.namedPlans == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPlans[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Addon) appendNamedPlans(name string, edges ...*Plan) {
	if _m.Edges.namedPlans == nil {
		_m.Edges.namedPlans = make(map[string][]*Plan)
	}
	if len(edges) == 0 {
		_m.Edges.namedPlans[name] = []*Plan{}
	} else {
		_m.Edges.namedPlans[name] = append(_m.Edges.namedPlans[name], edges...)
	}
}

// Addons is a parsable slice of Addon.
type Addons []*Addon
