// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/addon"
	"github.com/deicod/tarife/ent/plan"
	"github.com/rs/xid"
)

// AddonCreate is the builder for creating a Addon entity.
type AddonCreate struct {
	config
	mutation *AddonMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AddonCreate) SetName(v string) *AddonCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMonthlyFeeCents sets the "monthly_fee_cents" field.
func (_c *AddonCreate) SetMonthlyFeeCents(v int) *AddonCreate {
	_c.mutation.SetMonthlyFeeCents(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AddonCreate) SetID(v xid.ID) *AddonCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AddonCreate) SetNillableID(v *xid.ID) *AddonCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_c *AddonCreate) AddPlanIDs(ids ...xid.ID) *AddonCreate {
	_c.mutation.AddPlanIDs(ids...)
	return _c
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_c *AddonCreate) AddPlans(v ...*Plan) *AddonCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlanIDs(ids...)
}

// Mutation returns the AddonMutation object of the builder.
func (_c *AddonCreate) Mutation() *AddonMutation {
	return _c.mutation
}

// Save creates the Addon in the database.
func (_c *AddonCreate) Save(ctx context.Context) (*Addon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AddonCreate) SaveX(ctx context.Context) *Addon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AddonCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := addon.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AddonCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Addon.name"`)}
	}
	if _, ok := _c.mutation.MonthlyFeeCents(); !ok {
		return &ValidationError{Name: "monthly_fee_cents", err: errors.New(`ent: missing required field "Addon.monthly_fee_cents"`)}
	}
	return nil
}

func (_c *AddonCreate) sqlSave(ctx context.Context) (*Addon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AddonCreate) createSpec() (*Addon, *sqlgraph.CreateSpec) {
	var (
		_node = &Addon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(addon.Table, sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(addon.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.MonthlyFeeCents(); ok {
		_spec.SetField(addon.FieldMonthlyFeeCents, field.TypeInt, value)
		_node.MonthlyFeeCents = value
	}
	if nodes := _c.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   addon.PlansTable,
			Columns: addon.PlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AddonCreateBulk is the builder for creating many Addon entities in bulk.
type AddonCreateBulk struct {
	config
	err      error
	builders []*AddonCreate
}

// Save creates the Addon entities in the database.
func (_c *AddonCreateBulk) Save(ctx context.Context) ([]*Addon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Addon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AddonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AddonCreateBulk) SaveX(ctx context.Context) []*Addon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
