// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/bandwidth"
	"github.com/deicod/tarife/ent/plan"
	"github.com/rs/xid"
)

// BandwidthCreate is the builder for creating a Bandwidth entity.
type BandwidthCreate struct {
	config
	mutation *BandwidthMutation
	hooks    []Hook
}

// SetDownMbps sets the "down_mbps" field.
func (_c *BandwidthCreate) SetDownMbps(v int) *BandwidthCreate {
	_c.mutation.SetDownMbps(v)
	return _c
}

// SetUpMbps sets the "up_mbps" field.
func (_c *BandwidthCreate) SetUpMbps(v int) *BandwidthCreate {
	_c.mutation.SetUpMbps(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BandwidthCreate) SetID(v xid.ID) *BandwidthCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BandwidthCreate) SetNillableID(v *xid.ID) *BandwidthCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_c *BandwidthCreate) SetPlanID(id xid.ID) *BandwidthCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *BandwidthCreate) SetPlan(v *Plan) *BandwidthCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the BandwidthMutation object of the builder.
func (_c *BandwidthCreate) Mutation() *BandwidthMutation {
	return _c.mutation
}

// Save creates the Bandwidth in the database.
func (_c *BandwidthCreate) Save(ctx context.Context) (*Bandwidth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BandwidthCreate) SaveX(ctx context.Context) *Bandwidth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BandwidthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BandwidthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BandwidthCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := bandwidth.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BandwidthCreate) check() error {
	if _, ok := _c.mutation.DownMbps(); !ok {
		return &ValidationError{Name: "down_mbps", err: errors.New(`ent: missing required field "Bandwidth.down_mbps"`)}
	}
	if _, ok := _c.mutation.UpMbps(); !ok {
		return &ValidationError{Name: "up_mbps", err: errors.New(`ent: missing required field "Bandwidth.up_mbps"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "Bandwidth.plan"`)}
	}
	return nil
}

func (_c *BandwidthCreate) sqlSave(ctx context.Context) (*Bandwidth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BandwidthCreate) createSpec() (*Bandwidth, *sqlgraph.CreateSpec) {
	var (
		_node = &Bandwidth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bandwidth.Table, sqlgraph.NewFieldSpec(bandwidth.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DownMbps(); ok {
		_spec.SetField(bandwidth.FieldDownMbps, field.TypeInt, value)
		_node.DownMbps = value
	}
	if value, ok := _c.mutation.UpMbps(); ok {
		_spec.SetField(bandwidth.FieldUpMbps, field.TypeInt, value)
		_node.UpMbps = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bandwidth.PlanTable,
			Columns: []string{bandwidth.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.plan_bandwidth = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BandwidthCreateBulk is the builder for creating many Bandwidth entities in bulk.
type BandwidthCreateBulk struct {
	config
	err      error
	builders []*BandwidthCreate
}

// Save creates the Bandwidth entities in the database.
func (_c *BandwidthCreateBulk) Save(ctx context.Context) ([]*Bandwidth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bandwidth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BandwidthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BandwidthCreateBulk) SaveX(ctx context.Context) []*Bandwidth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BandwidthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BandwidthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
