// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/onetimefee"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/rs/xid"
)

// OneTimeFeeUpdate is the builder for updating OneTimeFee entities.
type OneTimeFeeUpdate struct {
	config
	hooks     []Hook
	mutation  *OneTimeFeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OneTimeFeeUpdate builder.
func (_u *OneTimeFeeUpdate) Where(ps ...predicate.OneTimeFee) *OneTimeFeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *OneTimeFeeUpdate) SetKind(v onetimefee.Kind) *OneTimeFeeUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OneTimeFeeUpdate) SetNillableKind(v *onetimefee.Kind) *OneTimeFeeUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *OneTimeFeeUpdate) SetAmountCents(v int) *OneTimeFeeUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *OneTimeFeeUpdate) SetNillableAmountCents(v *int) *OneTimeFeeUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *OneTimeFeeUpdate) AddAmountCents(v int) *OneTimeFeeUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *OneTimeFeeUpdate) SetPlanID(id xid.ID) *OneTimeFeeUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *OneTimeFeeUpdate) SetPlan(v *Plan) *OneTimeFeeUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the OneTimeFeeMutation object of the builder.
func (_u *OneTimeFeeUpdate) Mutation() *OneTimeFeeMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *OneTimeFeeUpdate) ClearPlan() *OneTimeFeeUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OneTimeFeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OneTimeFeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OneTimeFeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OneTimeFeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OneTimeFeeUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := onetimefee.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OneTimeFee.kind": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OneTimeFee.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OneTimeFeeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OneTimeFeeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OneTimeFeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onetimefee.Table, onetimefee.Columns, sqlgraph.NewFieldSpec(onetimefee.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(onetimefee.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(onetimefee.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(onetimefee.FieldAmountCents, field.TypeInt, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   onetimefee.PlanTable,
			Columns: []string{onetimefee.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   onetimefee.PlanTable,
			Columns: []string{onetimefee.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onetimefee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OneTimeFeeUpdateOne is the builder for updating a single OneTimeFee entity.
type OneTimeFeeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OneTimeFeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetKind sets the "kind" field.
func (_u *OneTimeFeeUpdateOne) SetKind(v onetimefee.Kind) *OneTimeFeeUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OneTimeFeeUpdateOne) SetNillableKind(v *onetimefee.Kind) *OneTimeFeeUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *OneTimeFeeUpdateOne) SetAmountCents(v int) *OneTimeFeeUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *OneTimeFeeUpdateOne) SetNillableAmountCents(v *int) *OneTimeFeeUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *OneTimeFeeUpdateOne) AddAmountCents(v int) *OneTimeFeeUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *OneTimeFeeUpdateOne) SetPlanID(id xid.ID) *OneTimeFeeUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *OneTimeFeeUpdateOne) SetPlan(v *Plan) *OneTimeFeeUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the OneTimeFeeMutation object of the builder.
func (_u *OneTimeFeeUpdateOne) Mutation() *OneTimeFeeMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *OneTimeFeeUpdateOne) ClearPlan() *OneTimeFeeUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the OneTimeFeeUpdate builder.
func (_u *OneTimeFeeUpdateOne) Where(ps ...predicate.OneTimeFee) *OneTimeFeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OneTimeFeeUpdateOne) Select(field string, fields ...string) *OneTimeFeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OneTimeFee entity.
func (_u *OneTimeFeeUpdateOne) Save(ctx context.Context) (*OneTimeFee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OneTimeFeeUpdateOne) SaveX(ctx context.Context) *OneTimeFee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OneTimeFeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OneTimeFeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OneTimeFeeUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := onetimefee.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "OneTimeFee.kind": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OneTimeFee.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OneTimeFeeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OneTimeFeeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OneTimeFeeUpdateOne) sqlSave(ctx context.Context) (_node *OneTimeFee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onetimefee.Table, onetimefee.Columns, sqlgraph.NewFieldSpec(onetimefee.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OneTimeFee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onetimefee.FieldID)
		for _, f := range fields {
			if !onetimefee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onetimefee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(onetimefee.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(onetimefee.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(onetimefee.FieldAmountCents, field.TypeInt, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   onetimefee.PlanTable,
			Columns: []string{onetimefee.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   onetimefee.PlanTable,
			Columns: []string{onetimefee.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OneTimeFee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onetimefee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
