// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/tarife/ent/onetimefee"
	"github.com/deicod/tarife/ent/plan"
	"github.com/rs/xid"
)

// OneTimeFee is the model entity for the OneTimeFee schema.
type OneTimeFee struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind onetimefee.Kind `json:"kind,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents int `json:"amount_cents,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OneTimeFeeQuery when eager-loading is set.
	Edges              OneTimeFeeEdges `json:"edges"`
	plan_one_time_fees *xid.ID
	selectValues       sql.SelectValues
}

// OneTimeFeeEdges holds the relations/edges for other nodes in the graph.
type OneTimeFeeEdges struct {
	// Plan holds the value of the plan edge.
	Plan *Plan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OneTimeFeeEdges) PlanOrErr() (*Plan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OneTimeFee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onetimefee.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case onetimefee.FieldKind:
			values[i] = new(sql.NullString)
		case onetimefee.FieldID:
			values[i] = new(xid.ID)
		case onetimefee.ForeignKeys[0]: // plan_one_time_fees
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OneTimeFee fields.
func (_m *OneTimeFee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onetimefee.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case onetimefee.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = onetimefee.Kind(value.String)
			}
		case onetimefee.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = int(value.Int64)
			}
		case onetimefee.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field plan_one_time_fees", values[i])
			} else if value.Valid {
				_m.plan_one_time_fees = new(xid.ID)
				*_m.plan_one_time_fees = *value.S.(*xid.ID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OneTimeFee.
// This includes values selected through modifiers, order, etc.
func (_m *OneTimeFee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the OneTimeFee entity.
func (_m *OneTimeFee) QueryPlan() *PlanQuery {
	return NewOneTimeFeeClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this OneTimeFee.
// Note that you need to call OneTimeFee.Unwrap() before calling this method if this OneTimeFee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OneTimeFee) Update() *OneTimeFeeUpdateOne {
	return NewOneTimeFeeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OneTimeFee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OneTimeFee) Unwrap() *OneTimeFee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OneTimeFee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OneTimeFee) String() string {
	var builder strings.Builder
	builder.WriteString("OneTimeFee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteByte(')')
	return builder.String()
}

// OneTimeFees is a parsable slice of OneTimeFee.
type OneTimeFees []*OneTimeFee
