// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/tarife/ent/bandwidth"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/provider"
	"github.com/rs/xid"
)

// Plan is the model entity for the Plan schema.
type Plan struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// Technology holds the value of the "technology" field.
	Technology plan.Technology `json:"technology,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// MinTermMonths holds the value of the "min_term_months" field.
	MinTermMonths int `json:"min_term_months,omitempty"`
	// CancelNoticeDays holds the value of the "cancel_notice_days" field.
	CancelNoticeDays int `json:"cancel_notice_days,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidTo holds the value of the "valid_to" field.
	ValidTo time.Time `json:"valid_to,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// VersionTag holds the value of the "version_tag" field.
	VersionTag string `json:"version_tag,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlanQuery when eager-loading is set.
	Edges          PlanEdges `json:"edges"`
	provider_plans *xid.ID
	selectValues   sql.SelectValues
}

// PlanEdges holds the relations/edges for other nodes in the graph.
type PlanEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Provider `json:"provider,omitempty"`
	// Bandwidth holds the value of the bandwidth edge.
	Bandwidth *Bandwidth `json:"bandwidth,omitempty"`
	// PriceTiers holds the value of the price_tiers edge.
	PriceTiers []*PriceTier `json:"price_tiers,omitempty"`
	// OneTimeFees holds the value of the one_time_fees edge.
	OneTimeFees []*OneTimeFee `json:"one_time_fees,omitempty"`
	// Promos holds the value of the promos edge.
	Promos []*Promo `json:"promos,omitempty"`
	// Addon holds the value of the addon edge.
	Addon []*Addon `json:"addon,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
	// totalCount holds the count of the edges above.
	totalCount [6]map[string]int

	namedPriceTiers  map[string][]*PriceTier
	namedOneTimeFees map[string][]*OneTimeFee
	namedPromos      map[string][]*Promo
	namedAddon       map[string][]*Addon
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlanEdges) ProviderOrErr() (*Provider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: provider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// BandwidthOrErr returns the Bandwidth value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlanEdges) BandwidthOrErr() (*Bandwidth, error) {
	if e.Bandwidth != nil {
		return e.Bandwidth, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: bandwidth.Label}
	}
	return nil, &NotLoadedError{edge: "bandwidth"}
}

// PriceTiersOrErr returns the PriceTiers value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) PriceTiersOrErr() ([]*PriceTier, error) {
	if e.loadedTypes[2] {
		return e.PriceTiers, nil
	}
	return nil, &NotLoadedError{edge: "price_tiers"}
}

// OneTimeFeesOrErr returns the OneTimeFees value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) OneTimeFeesOrErr() ([]*OneTimeFee, error) {
	if e.loadedTypes[3] {
		return e.OneTimeFees, nil
	}
	return nil, &NotLoadedError{edge: "one_time_fees"}
}

// PromosOrErr returns the Promos value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) PromosOrErr() ([]*Promo, error) {
	if e.loadedTypes[4] {
		return e.Promos, nil
	}
	return nil, &NotLoadedError{edge: "promos"}
}

// AddonOrErr returns the Addon value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) AddonOrErr() ([]*Addon, error) {
	if e.loadedTypes[5] {
		return e.Addon, nil
	}
	return nil, &NotLoadedError{edge: "addon"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plan.FieldMinTermMonths, plan.FieldCancelNoticeDays:
			values[i] = new(sql.NullInt64)
		case plan.FieldTechnology, plan.FieldName, plan.FieldDescription, plan.FieldSourceURL, plan.FieldVersionTag:
			values[i] = new(sql.NullString)
		case plan.FieldValidFrom, plan.FieldValidTo:
			values[i] = new(sql.NullTime)
		case plan.FieldID:
			values[i] = new(xid.ID)
		case plan.ForeignKeys[0]: // provider_plans
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plan fields.
func (_m *Plan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case plan.FieldTechnology:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field technology", values[i])
			} else if value.Valid {
				_m.Technology = plan.Technology(value.String)
			}
		case plan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case plan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case plan.FieldMinTermMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_term_months", values[i])
			} else if value.Valid {
				_m.MinTermMonths = int(value.Int64)
			}
		case plan.FieldCancelNoticeDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_notice_days", values[i])
			} else if value.Valid {
				_m.CancelNoticeDays = int(value.Int64)
			}
		case plan.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case plan.FieldValidTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_to", values[i])
			} else if value.Valid {
				_m.ValidTo = value.Time
			}
		case plan.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case plan.FieldVersionTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version_tag", values[i])
			} else if value.Valid {
				_m.VersionTag = value.String
			}
		case plan.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field provider_plans", values[i])
			} else if value.Valid {
				_m.provider_plans = new(xid.ID)
				*_m.provider_plans = *value.S.(*xid.ID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plan.
// This includes values selected through modifiers, order, etc.
func (_m *Plan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the Plan entity.
func (_m *Plan) QueryProvider() *ProviderQuery {
	return NewPlanClient(_m.config).QueryProvider(_m)
}

// QueryBandwidth queries the "bandwidth" edge of the Plan entity.
func (_m *Plan) QueryBandwidth() *BandwidthQuery {
	return NewPlanClient(_m.config).QueryBandwidth(_m)
}

// QueryPriceTiers queries the "price_tiers" edge of the Plan entity.
func (_m *Plan) QueryPriceTiers() *PriceTierQuery {
	return NewPlanClient(_m.config).QueryPriceTiers(_m)
}

// QueryOneTimeFees queries the "one_time_fees" edge of the Plan entity.
func (_m *Plan) QueryOneTimeFees() *OneTimeFeeQuery {
	return NewPlanClient(_m.config).QueryOneTimeFees(_m)
}

// QueryPromos queries the "promos" edge of the Plan entity.
func (_m *Plan) QueryPromos() *PromoQuery {
	return NewPlanClient(_m.config).QueryPromos(_m)
}

// QueryAddon queries the "addon" edge of the Plan entity.
func (_m *Plan) QueryAddon() *AddonQuery {
	return NewPlanClient(_m.config).QueryAddon(_m)
}

// Update returns a builder for updating this Plan.
// Note that you need to call Plan.Unwrap() before calling this method if this Plan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plan) Update() *PlanUpdateOne {
	return NewPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plan) Unwrap() *Plan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plan) String() string {
	var builder strings.Builder
	builder.WriteString("Plan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("technology=")
	builder.WriteString(fmt.Sprintf("%v", _m.Technology))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("min_term_months=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinTermMonths))
	builder.WriteString(", ")
	builder.WriteString("cancel_notice_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.CancelNoticeDays))
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("valid_to=")
	builder.WriteString(_m.ValidTo.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("version_tag=")
	builder.WriteString(_m.VersionTag)
	builder.WriteByte(')')
	return builder.String()
}

// NamedPriceTiers returns the PriceTiers named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Plan) NamedPriceTiers(name string) ([]*PriceTier, error) {
	if _m.Edges.namedPriceTiers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPriceTiers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Plan) appendNamedPriceTiers(name string, edges ...*PriceTier) {
	if _m.Edges.namedPriceTiers == nil {
		_m.Edges.namedPriceTiers = make(map[string][]*PriceTier)
	}
	if len(edges) == 0 {
		_m.Edges.namedPriceTiers[name] = []*PriceTier{}
	} else {
		_m.Edges.namedPriceTiers[name] = append(_m.Edges.namedPriceTiers[name], edges...)
	}
}

// NamedOneTimeFees returns the OneTimeFees named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Plan) NamedOneTimeFees(name string) ([]*OneTimeFee, error) {
	if _m.Edges.namedOneTimeFees == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedOneTimeFees[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Plan) appendNamedOneTimeFees(name string, edges ...*OneTimeFee) {
	if _m.Edges.namedOneTimeFees == nil {
		_m.Edges.namedOneTimeFees = make(map[string][]*OneTimeFee)
	}
	if len(edges) == 0 {
		_m.Edges.namedOneTimeFees[name] = []*OneTimeFee{}
	} else {
		_m.Edges.namedOneTimeFees[name] = append(_m.Edges.namedOneTimeFees[name], edges...)
	}
}

// NamedPromos returns the Promos named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Plan) NamedPromos(name string) ([]*Promo, error) {
	if _m.Edges.namedPromos == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPromos[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Plan) appendNamedPromos(name string, edges ...*Promo) {
	if _m.Edges.namedPromos == nil {
		_m.Edges.namedPromos = make(map[string][]*Promo)
	}
	if len(edges) == 0 {
		_m.Edges.namedPromos[name] = []*Promo{}
	} else {
		_m.Edges.namedPromos[name] = append(_m.Edges.namedPromos[name], edges...)
	}
}

// NamedAddon returns the Addon named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Plan) NamedAddon(name string) ([]*Addon, error) {
	if _m.Edges.namedAddon == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedAddon[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Plan) appendNamedAddon(name string, edges ...*Addon) {
	if _m.Edges.namedAddon == nil {
		_m.Edges.namedAddon = make(map[string][]*Addon)
	}
	if len(edges) == 0 {
		_m.Edges.namedAddon[name] = []*Addon{}
	} else {
		_m.Edges.namedAddon[name] = append(_m.Edges.namedAddon[name], edges...)
	}
}

// Plans is a parsable slice of Plan.
type Plans []*Plan
