// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/addon"
	"github.com/deicod/tarife/ent/bandwidth"
	"github.com/deicod/tarife/ent/onetimefee"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/deicod/tarife/ent/pricetier"
	"github.com/deicod/tarife/ent/promo"
	"github.com/deicod/tarife/ent/provider"
	"github.com/rs/xid"
)

// PlanQuery is the builder for querying Plan entities.
type PlanQuery struct {
	config
	ctx                  *QueryContext
	order                []plan.OrderOption
	inters               []Interceptor
	predicates           []predicate.Plan
	withProvider         *ProviderQuery
	withBandwidth        *BandwidthQuery
	withPriceTiers       *PriceTierQuery
	withOneTimeFees      *OneTimeFeeQuery
	withPromos           *PromoQuery
	withAddon            *AddonQuery
	withFKs              bool
	loadTotal            []func(context.Context, []*Plan) error
	modifiers            []func(*sql.Selector)
	withNamedPriceTiers  map[string]*PriceTierQuery
	withNamedOneTimeFees map[string]*OneTimeFeeQuery
	withNamedPromos      map[string]*PromoQuery
	withNamedAddon       map[string]*AddonQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlanQuery builder.
func (_q *PlanQuery) Where(ps ...predicate.Plan) *PlanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PlanQuery) Limit(limit int) *PlanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PlanQuery) Offset(offset int) *PlanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PlanQuery) Unique(unique bool) *PlanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PlanQuery) Order(o ...plan.OrderOption) *PlanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *PlanQuery) QueryProvider() *ProviderQuery {
	query := (&ProviderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(provider.Table, provider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, plan.ProviderTable, plan.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBandwidth chains the current query on the "bandwidth" edge.
func (_q *PlanQuery) QueryBandwidth() *BandwidthQuery {
	query := (&BandwidthClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(bandwidth.Table, bandwidth.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, plan.BandwidthTable, plan.BandwidthColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPriceTiers chains the current query on the "price_tiers" edge.
func (_q *PlanQuery) QueryPriceTiers() *PriceTierQuery {
	query := (&PriceTierClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(pricetier.Table, pricetier.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, plan.PriceTiersTable, plan.PriceTiersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOneTimeFees chains the current query on the "one_time_fees" edge.
func (_q *PlanQuery) QueryOneTimeFees() *OneTimeFeeQuery {
	query := (&OneTimeFeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(onetimefee.Table, onetimefee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, plan.OneTimeFeesTable, plan.OneTimeFeesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPromos chains the current query on the "promos" edge.
func (_q *PlanQuery) QueryPromos() *PromoQuery {
	query := (&PromoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(promo.Table, promo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, plan.PromosTable, plan.PromosColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAddon chains the current query on the "addon" edge.
func (_q *PlanQuery) QueryAddon() *AddonQuery {
	query := (&AddonClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, selector),
			sqlgraph.To(addon.Table, addon.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, plan.AddonTable, plan.AddonPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Plan entity from the query.
// Returns a *NotFoundError when no Plan was found.
func (_q *PlanQuery) First(ctx context.Context) (*Plan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{plan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PlanQuery) FirstX(ctx context.Context) *Plan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Plan ID from the query.
// Returns a *NotFoundError when no Plan ID was found.
func (_q *PlanQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{plan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PlanQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Plan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Plan entity is found.
// Returns a *NotFoundError when no Plan entities are found.
func (_q *PlanQuery) Only(ctx context.Context) (*Plan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{plan.Label}
	default:
		return nil, &NotSingularError{plan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PlanQuery) OnlyX(ctx context.Context) *Plan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Plan ID in the query.
// Returns a *NotSingularError when more than one Plan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PlanQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{plan.Label}
	default:
		err = &NotSingularError{plan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PlanQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Plans.
func (_q *PlanQuery) All(ctx context.Context) ([]*Plan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Plan, *PlanQuery]()
	return withInterceptors[[]*Plan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PlanQuery) AllX(ctx context.Context) []*Plan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Plan IDs.
func (_q *PlanQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(plan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PlanQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PlanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PlanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PlanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PlanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PlanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PlanQuery) Clone() *PlanQuery {
	if _q == nil {
		return nil
	}
	return &PlanQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]plan.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Plan{}, _q.predicates...),
		withProvider:    _q.withProvider.Clone(),
		withBandwidth:   _q.withBandwidth.Clone(),
		withPriceTiers:  _q.withPriceTiers.Clone(),
		withOneTimeFees: _q.withOneTimeFees.Clone(),
		withPromos:      _q.withPromos.Clone(),
		withAddon:       _q.withAddon.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithProvider(opts ...func(*ProviderQuery)) *PlanQuery {
	query := (&ProviderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// WithBandwidth tells the query-builder to eager-load the nodes that are connected to
// the "bandwidth" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithBandwidth(opts ...func(*BandwidthQuery)) *PlanQuery {
	query := (&BandwidthClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBandwidth = query
	return _q
}

// WithPriceTiers tells the query-builder to eager-load the nodes that are connected to
// the "price_tiers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithPriceTiers(opts ...func(*PriceTierQuery)) *PlanQuery {
	query := (&PriceTierClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPriceTiers = query
	return _q
}

// WithOneTimeFees tells the query-builder to eager-load the nodes that are connected to
// the "one_time_fees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithOneTimeFees(opts ...func(*OneTimeFeeQuery)) *PlanQuery {
	query := (&OneTimeFeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOneTimeFees = query
	return _q
}

// WithPromos tells the query-builder to eager-load the nodes that are connected to
// the "promos" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithPromos(opts ...func(*PromoQuery)) *PlanQuery {
	query := (&PromoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPromos = query
	return _q
}

// WithAddon tells the query-builder to eager-load the nodes that are connected to
// the "addon" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithAddon(opts ...func(*AddonQuery)) *PlanQuery {
	query := (&AddonClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAddon = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Technology plan.Technology `json:"technology,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Plan.Query().
//		GroupBy(plan.FieldTechnology).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PlanQuery) GroupBy(field string, fields ...string) *PlanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = plan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Technology plan.Technology `json:"technology,omitempty"`
//	}
//
//	client.Plan.Query().
//		Select(plan.FieldTechnology).
//		Scan(ctx, &v)
func (_q *PlanQuery) Select(fields ...string) *PlanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PlanSelect{PlanQuery: _q}
	sbuild.label = plan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlanSelect configured with the given aggregations.
func (_q *PlanQuery) Aggregate(fns ...AggregateFunc) *PlanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PlanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !plan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PlanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Plan, error) {
	var (
		nodes       = []*Plan{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withProvider != nil,
			_q.withBandwidth != nil,
			_q.withPriceTiers != nil,
			_q.withOneTimeFees != nil,
			_q.withPromos != nil,
			_q.withAddon != nil,
		}
	)
	if _q.withProvider != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, plan.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Plan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Plan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *Plan, e *Provider) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBandwidth; query != nil {
		if err := _q.loadBandwidth(ctx, query, nodes, nil,
			func(n *Plan, e *Bandwidth) { n.Edges.Bandwidth = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPriceTiers; query != nil {
		if err := _q.loadPriceTiers(ctx, query, nodes,
			func(n *Plan) { n.Edges.PriceTiers = []*PriceTier{} },
			func(n *Plan, e *PriceTier) { n.Edges.PriceTiers = append(n.Edges.PriceTiers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOneTimeFees; query != nil {
		if err := _q.loadOneTimeFees(ctx, query, nodes,
			func(n *Plan) { n.Edges.OneTimeFees = []*OneTimeFee{} },
			func(n *Plan, e *OneTimeFee) { n.Edges.OneTimeFees = append(n.Edges.OneTimeFees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPromos; query != nil {
		if err := _q.loadPromos(ctx, query, nodes,
			func(n *Plan) { n.Edges.Promos = []*Promo{} },
			func(n *Plan, e *Promo) { n.Edges.Promos = append(n.Edges.Promos, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAddon; query != nil {
		if err := _q.loadAddon(ctx, query, nodes,
			func(n *Plan) { n.Edges.Addon = []*Addon{} },
			func(n *Plan, e *Addon) { n.Edges.Addon = append(n.Edges.Addon, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedPriceTiers {
		if err := _q.loadPriceTiers(ctx, query, nodes,
			func(n *Plan) { n.appendNamedPriceTiers(name) },
			func(n *Plan, e *PriceTier) { n.appendNamedPriceTiers(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedOneTimeFees {
		if err := _q.loadOneTimeFees(ctx, query, nodes,
			func(n *Plan) { n.appendNamedOneTimeFees(name) },
			func(n *Plan, e *OneTimeFee) { n.appendNamedOneTimeFees(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedPromos {
		if err := _q.loadPromos(ctx, query, nodes,
			func(n *Plan) { n.appendNamedPromos(name) },
			func(n *Plan, e *Promo) { n.appendNamedPromos(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedAddon {
		if err := _q.loadAddon(ctx, query, nodes,
			func(n *Plan) { n.appendNamedAddon(name) },
			func(n *Plan, e *Addon) { n.appendNamedAddon(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PlanQuery) loadProvider(ctx context.Context, query *ProviderQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *Provider)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*Plan)
	for i := range nodes {
		if nodes[i].provider_plans == nil {
			continue
		}
		fk := *nodes[i].provider_plans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(provider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_plans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlanQuery) loadBandwidth(ctx context.Context, query *BandwidthQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *Bandwidth)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Plan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Bandwidth(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(plan.BandwidthColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.plan_bandwidth
		if fk == nil {
			return fmt.Errorf(`foreign-key "plan_bandwidth" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_bandwidth" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlanQuery) loadPriceTiers(ctx context.Context, query *PriceTierQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *PriceTier)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Plan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PriceTier(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(plan.PriceTiersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.plan_price_tiers
		if fk == nil {
			return fmt.Errorf(`foreign-key "plan_price_tiers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_price_tiers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlanQuery) loadOneTimeFees(ctx context.Context, query *OneTimeFeeQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *OneTimeFee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Plan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.OneTimeFee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(plan.OneTimeFeesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.plan_one_time_fees
		if fk == nil {
			return fmt.Errorf(`foreign-key "plan_one_time_fees" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_one_time_fees" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlanQuery) loadPromos(ctx context.Context, query *PromoQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *Promo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Plan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Promo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(plan.PromosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.plan_promos
		if fk == nil {
			return fmt.Errorf(`foreign-key "plan_promos" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_promos" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlanQuery) loadAddon(ctx context.Context, query *AddonQuery, nodes []*Plan, init func(*Plan), assign func(*Plan, *Addon)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[xid.ID]*Plan)
	nids := make(map[xid.ID]map[*Plan]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(plan.AddonTable)
		s.Join(joinT).On(s.C(addon.FieldID), joinT.C(plan.AddonPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(plan.AddonPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(plan.AddonPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(xid.ID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*xid.ID)
				inValue := *values[1].(*xid.ID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Plan]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Addon](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "addon" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *PlanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PlanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for i := range fields {
			if fields[i] != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PlanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(plan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = plan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *PlanQuery) Modify(modifiers ...func(s *sql.Selector)) *PlanSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedPriceTiers tells the query-builder to eager-load the nodes that are connected to the "price_tiers"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithNamedPriceTiers(name string, opts ...func(*PriceTierQuery)) *PlanQuery {
	query := (&PriceTierClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedPriceTiers == nil {
		_q.withNamedPriceTiers = make(map[string]*PriceTierQuery)
	}
	_q.withNamedPriceTiers[name] = query
	return _q
}

// WithNamedOneTimeFees tells the query-builder to eager-load the nodes that are connected to the "one_time_fees"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithNamedOneTimeFees(name string, opts ...func(*OneTimeFeeQuery)) *PlanQuery {
	query := (&OneTimeFeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedOneTimeFees == nil {
		_q.withNamedOneTimeFees = make(map[string]*OneTimeFeeQuery)
	}
	_q.withNamedOneTimeFees[name] = query
	return _q
}

// WithNamedPromos tells the query-builder to eager-load the nodes that are connected to the "promos"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithNamedPromos(name string, opts ...func(*PromoQuery)) *PlanQuery {
	query := (&PromoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedPromos == nil {
		_q.withNamedPromos = make(map[string]*PromoQuery)
	}
	_q.withNamedPromos[name] = query
	return _q
}

// WithNamedAddon tells the query-builder to eager-load the nodes that are connected to the "addon"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanQuery) WithNamedAddon(name string, opts ...func(*AddonQuery)) *PlanQuery {
	query := (&AddonClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedAddon == nil {
		_q.withNamedAddon = make(map[string]*AddonQuery)
	}
	_q.withNamedAddon[name] = query
	return _q
}

// PlanGroupBy is the group-by builder for Plan entities.
type PlanGroupBy struct {
	selector
	build *PlanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PlanGroupBy) Aggregate(fns ...AggregateFunc) *PlanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PlanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlanQuery, *PlanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PlanGroupBy) sqlScan(ctx context.Context, root *PlanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlanSelect is the builder for selecting fields of Plan entities.
type PlanSelect struct {
	*PlanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PlanSelect) Aggregate(fns ...AggregateFunc) *PlanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PlanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlanQuery, *PlanSelect](ctx, _s.PlanQuery, _s, _s.inters, v)
}

func (_s *PlanSelect) sqlScan(ctx context.Context, root *PlanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *PlanSelect) Modify(modifiers ...func(s *sql.Selector)) *PlanSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
