// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/addon"
	"github.com/deicod/tarife/ent/bandwidth"
	"github.com/deicod/tarife/ent/onetimefee"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/pricetier"
	"github.com/deicod/tarife/ent/promo"
	"github.com/deicod/tarife/ent/provider"
	"github.com/rs/xid"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
}

// SetTechnology sets the "technology" field.
func (_c *PlanCreate) SetTechnology(v plan.Technology) *PlanCreate {
	_c.mutation.SetTechnology(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PlanCreate) SetName(v string) *PlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlanCreate) SetDescription(v string) *PlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDescription(v *string) *PlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMinTermMonths sets the "min_term_months" field.
func (_c *PlanCreate) SetMinTermMonths(v int) *PlanCreate {
	_c.mutation.SetMinTermMonths(v)
	return _c
}

// SetNillableMinTermMonths sets the "min_term_months" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMinTermMonths(v *int) *PlanCreate {
	if v != nil {
		_c.SetMinTermMonths(*v)
	}
	return _c
}

// SetCancelNoticeDays sets the "cancel_notice_days" field.
func (_c *PlanCreate) SetCancelNoticeDays(v int) *PlanCreate {
	_c.mutation.SetCancelNoticeDays(v)
	return _c
}

// SetNillableCancelNoticeDays sets the "cancel_notice_days" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCancelNoticeDays(v *int) *PlanCreate {
	if v != nil {
		_c.SetCancelNoticeDays(*v)
	}
	return _c
}

// SetValidFrom sets the "valid_from" field.
func (_c *PlanCreate) SetValidFrom(v time.Time) *PlanCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetValidTo sets the "valid_to" field.
func (_c *PlanCreate) SetValidTo(v time.Time) *PlanCreate {
	_c.mutation.SetValidTo(v)
	return _c
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_c *PlanCreate) SetNillableValidTo(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetValidTo(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *PlanCreate) SetSourceURL(v string) *PlanCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetVersionTag sets the "version_tag" field.
func (_c *PlanCreate) SetVersionTag(v string) *PlanCreate {
	_c.mutation.SetVersionTag(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PlanCreate) SetID(v xid.ID) *PlanCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlanCreate) SetNillableID(v *xid.ID) *PlanCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProviderID sets the "provider" edge to the Provider entity by ID.
func (_c *PlanCreate) SetProviderID(id xid.ID) *PlanCreate {
	_c.mutation.SetProviderID(id)
	return _c
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *PlanCreate) SetProvider(v *Provider) *PlanCreate {
	return _c.SetProviderID(v.ID)
}

// SetBandwidthID sets the "bandwidth" edge to the Bandwidth entity by ID.
func (_c *PlanCreate) SetBandwidthID(id xid.ID) *PlanCreate {
	_c.mutation.SetBandwidthID(id)
	return _c
}

// SetNillableBandwidthID sets the "bandwidth" edge to the Bandwidth entity by ID if the given value is not nil.
func (_c *PlanCreate) SetNillableBandwidthID(id *xid.ID) *PlanCreate {
	if id != nil {
		_c = _c.SetBandwidthID(*id)
	}
	return _c
}

// SetBandwidth sets the "bandwidth" edge to the Bandwidth entity.
func (_c *PlanCreate) SetBandwidth(v *Bandwidth) *PlanCreate {
	return _c.SetBandwidthID(v.ID)
}

// AddPriceTierIDs adds the "price_tiers" edge to the PriceTier entity by IDs.
func (_c *PlanCreate) AddPriceTierIDs(ids ...xid.ID) *PlanCreate {
	_c.mutation.AddPriceTierIDs(ids...)
	return _c
}

// AddPriceTiers adds the "price_tiers" edges to the PriceTier entity.
func (_c *PlanCreate) AddPriceTiers(v ...*PriceTier) *PlanCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPriceTierIDs(ids...)
}

// AddOneTimeFeeIDs adds the "one_time_fees" edge to the OneTimeFee entity by IDs.
func (_c *PlanCreate) AddOneTimeFeeIDs(ids ...xid.ID) *PlanCreate {
	_c.mutation.AddOneTimeFeeIDs(ids...)
	return _c
}

// AddOneTimeFees adds the "one_time_fees" edges to the OneTimeFee entity.
func (_c *PlanCreate) AddOneTimeFees(v ...*OneTimeFee) *PlanCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOneTimeFeeIDs(ids...)
}

// AddPromoIDs adds the "promos" edge to the Promo entity by IDs.
func (_c *PlanCreate) AddPromoIDs(ids ...xid.ID) *PlanCreate {
	_c.mutation.AddPromoIDs(ids...)
	return _c
}

// AddPromos adds the "promos" edges to the Promo entity.
func (_c *PlanCreate) AddPromos(v ...*Promo) *PlanCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPromoIDs(ids...)
}

// AddAddonIDs adds the "addon" edge to the Addon entity by IDs.
func (_c *PlanCreate) AddAddonIDs(ids ...xid.ID) *PlanCreate {
	_c.mutation.AddAddonIDs(ids...)
	return _c
}

// AddAddon adds the "addon" edges to the Addon entity.
func (_c *PlanCreate) AddAddon(v ...*Addon) *PlanCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAddonIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() {
	if _, ok := _c.mutation.MinTermMonths(); !ok {
		v := plan.DefaultMinTermMonths
		_c.mutation.SetMinTermMonths(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := plan.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.Technology(); !ok {
		return &ValidationError{Name: "technology", err: errors.New(`ent: missing required field "Plan.technology"`)}
	}
	if v, ok := _c.mutation.Technology(); ok {
		if err := plan.TechnologyValidator(v); err != nil {
			return &ValidationError{Name: "technology", err: fmt.Errorf(`ent: validator failed for field "Plan.technology": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plan.name"`)}
	}
	if _, ok := _c.mutation.MinTermMonths(); !ok {
		return &ValidationError{Name: "min_term_months", err: errors.New(`ent: missing required field "Plan.min_term_months"`)}
	}
	if _, ok := _c.mutation.ValidFrom(); !ok {
		return &ValidationError{Name: "valid_from", err: errors.New(`ent: missing required field "Plan.valid_from"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "Plan.source_url"`)}
	}
	if _, ok := _c.mutation.VersionTag(); !ok {
		return &ValidationError{Name: "version_tag", err: errors.New(`ent: missing required field "Plan.version_tag"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "Plan.provider"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Technology(); ok {
		_spec.SetField(plan.FieldTechnology, field.TypeEnum, value)
		_node.Technology = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.MinTermMonths(); ok {
		_spec.SetField(plan.FieldMinTermMonths, field.TypeInt, value)
		_node.MinTermMonths = value
	}
	if value, ok := _c.mutation.CancelNoticeDays(); ok {
		_spec.SetField(plan.FieldCancelNoticeDays, field.TypeInt, value)
		_node.CancelNoticeDays = value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(plan.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = value
	}
	if value, ok := _c.mutation.ValidTo(); ok {
		_spec.SetField(plan.FieldValidTo, field.TypeTime, value)
		_node.ValidTo = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(plan.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.VersionTag(); ok {
		_spec.SetField(plan.FieldVersionTag, field.TypeString, value)
		_node.VersionTag = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.ProviderTable,
			Columns: []string{plan.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.provider_plans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BandwidthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   plan.BandwidthTable,
			Columns: []string{plan.BandwidthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bandwidth.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PriceTiersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.PriceTiersTable,
			Columns: []string{plan.PriceTiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricetier.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OneTimeFeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.OneTimeFeesTable,
			Columns: []string{plan.OneTimeFeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(onetimefee.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PromosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.PromosTable,
			Columns: []string{plan.PromosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AddonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   plan.AddonTable,
			Columns: plan.AddonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
