// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/deicod/tarife/ent/pricetier"
	"github.com/rs/xid"
)

// PriceTierUpdate is the builder for updating PriceTier entities.
type PriceTierUpdate struct {
	config
	hooks     []Hook
	mutation  *PriceTierMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PriceTierUpdate builder.
func (_u *PriceTierUpdate) Where(ps ...predicate.PriceTier) *PriceTierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStartMonth sets the "start_month" field.
func (_u *PriceTierUpdate) SetStartMonth(v int) *PriceTierUpdate {
	_u.mutation.ResetStartMonth()
	_u.mutation.SetStartMonth(v)
	return _u
}

// SetNillableStartMonth sets the "start_month" field if the given value is not nil.
func (_u *PriceTierUpdate) SetNillableStartMonth(v *int) *PriceTierUpdate {
	if v != nil {
		_u.SetStartMonth(*v)
	}
	return _u
}

// AddStartMonth adds value to the "start_month" field.
func (_u *PriceTierUpdate) AddStartMonth(v int) *PriceTierUpdate {
	_u.mutation.AddStartMonth(v)
	return _u
}

// SetEndMonth sets the "end_month" field.
func (_u *PriceTierUpdate) SetEndMonth(v int) *PriceTierUpdate {
	_u.mutation.ResetEndMonth()
	_u.mutation.SetEndMonth(v)
	return _u
}

// SetNillableEndMonth sets the "end_month" field if the given value is not nil.
func (_u *PriceTierUpdate) SetNillableEndMonth(v *int) *PriceTierUpdate {
	if v != nil {
		_u.SetEndMonth(*v)
	}
	return _u
}

// AddEndMonth adds value to the "end_month" field.
func (_u *PriceTierUpdate) AddEndMonth(v int) *PriceTierUpdate {
	_u.mutation.AddEndMonth(v)
	return _u
}

// SetMonthlyFeeCents sets the "monthly_fee_cents" field.
func (_u *PriceTierUpdate) SetMonthlyFeeCents(v int) *PriceTierUpdate {
	_u.mutation.ResetMonthlyFeeCents()
	_u.mutation.SetMonthlyFeeCents(v)
	return _u
}

// SetNillableMonthlyFeeCents sets the "monthly_fee_cents" field if the given value is not nil.
func (_u *PriceTierUpdate) SetNillableMonthlyFeeCents(v *int) *PriceTierUpdate {
	if v != nil {
		_u.SetMonthlyFeeCents(*v)
	}
	return _u
}

// AddMonthlyFeeCents adds value to the "monthly_fee_cents" field.
func (_u *PriceTierUpdate) AddMonthlyFeeCents(v int) *PriceTierUpdate {
	_u.mutation.AddMonthlyFeeCents(v)
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *PriceTierUpdate) SetPlanID(id xid.ID) *PriceTierUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *PriceTierUpdate) SetPlan(v *Plan) *PriceTierUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PriceTierMutation object of the builder.
func (_u *PriceTierUpdate) Mutation() *PriceTierMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *PriceTierUpdate) ClearPlan() *PriceTierUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceTierUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceTierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceTierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceTierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceTierUpdate) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceTier.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PriceTierUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PriceTierUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PriceTierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricetier.Table, pricetier.Columns, sqlgraph.NewFieldSpec(pricetier.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartMonth(); ok {
		_spec.SetField(pricetier.FieldStartMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartMonth(); ok {
		_spec.AddField(pricetier.FieldStartMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndMonth(); ok {
		_spec.SetField(pricetier.FieldEndMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndMonth(); ok {
		_spec.AddField(pricetier.FieldEndMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MonthlyFeeCents(); ok {
		_spec.SetField(pricetier.FieldMonthlyFeeCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthlyFeeCents(); ok {
		_spec.AddField(pricetier.FieldMonthlyFeeCents, field.TypeInt, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricetier.PlanTable,
			Columns: []string{pricetier.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricetier.PlanTable,
			Columns: []string{pricetier.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricetier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceTierUpdateOne is the builder for updating a single PriceTier entity.
type PriceTierUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PriceTierMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetStartMonth sets the "start_month" field.
func (_u *PriceTierUpdateOne) SetStartMonth(v int) *PriceTierUpdateOne {
	_u.mutation.ResetStartMonth()
	_u.mutation.SetStartMonth(v)
	return _u
}

// SetNillableStartMonth sets the "start_month" field if the given value is not nil.
func (_u *PriceTierUpdateOne) SetNillableStartMonth(v *int) *PriceTierUpdateOne {
	if v != nil {
		_u.SetStartMonth(*v)
	}
	return _u
}

// AddStartMonth adds value to the "start_month" field.
func (_u *PriceTierUpdateOne) AddStartMonth(v int) *PriceTierUpdateOne {
	_u.mutation.AddStartMonth(v)
	return _u
}

// SetEndMonth sets the "end_month" field.
func (_u *PriceTierUpdateOne) SetEndMonth(v int) *PriceTierUpdateOne {
	_u.mutation.ResetEndMonth()
	_u.mutation.SetEndMonth(v)
	return _u
}

// SetNillableEndMonth sets the "end_month" field if the given value is not nil.
func (_u *PriceTierUpdateOne) SetNillableEndMonth(v *int) *PriceTierUpdateOne {
	if v != nil {
		_u.SetEndMonth(*v)
	}
	return _u
}

// AddEndMonth adds value to the "end_month" field.
func (_u *PriceTierUpdateOne) AddEndMonth(v int) *PriceTierUpdateOne {
	_u.mutation.AddEndMonth(v)
	return _u
}

// SetMonthlyFeeCents sets the "monthly_fee_cents" field.
func (_u *PriceTierUpdateOne) SetMonthlyFeeCents(v int) *PriceTierUpdateOne {
	_u.mutation.ResetMonthlyFeeCents()
	_u.mutation.SetMonthlyFeeCents(v)
	return _u
}

// SetNillableMonthlyFeeCents sets the "monthly_fee_cents" field if the given value is not nil.
func (_u *PriceTierUpdateOne) SetNillableMonthlyFeeCents(v *int) *PriceTierUpdateOne {
	if v != nil {
		_u.SetMonthlyFeeCents(*v)
	}
	return _u
}

// AddMonthlyFeeCents adds value to the "monthly_fee_cents" field.
func (_u *PriceTierUpdateOne) AddMonthlyFeeCents(v int) *PriceTierUpdateOne {
	_u.mutation.AddMonthlyFeeCents(v)
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *PriceTierUpdateOne) SetPlanID(id xid.ID) *PriceTierUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *PriceTierUpdateOne) SetPlan(v *Plan) *PriceTierUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PriceTierMutation object of the builder.
func (_u *PriceTierUpdateOne) Mutation() *PriceTierMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *PriceTierUpdateOne) ClearPlan() *PriceTierUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the PriceTierUpdate builder.
func (_u *PriceTierUpdateOne) Where(ps ...predicate.PriceTier) *PriceTierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceTierUpdateOne) Select(field string, fields ...string) *PriceTierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PriceTier entity.
func (_u *PriceTierUpdateOne) Save(ctx context.Context) (*PriceTier, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceTierUpdateOne) SaveX(ctx context.Context) *PriceTier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceTierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceTierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceTierUpdateOne) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceTier.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PriceTierUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PriceTierUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PriceTierUpdateOne) sqlSave(ctx context.Context) (_node *PriceTier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricetier.Table, pricetier.Columns, sqlgraph.NewFieldSpec(pricetier.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceTier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricetier.FieldID)
		for _, f := range fields {
			if !pricetier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricetier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartMonth(); ok {
		_spec.SetField(pricetier.FieldStartMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartMonth(); ok {
		_spec.AddField(pricetier.FieldStartMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndMonth(); ok {
		_spec.SetField(pricetier.FieldEndMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndMonth(); ok {
		_spec.AddField(pricetier.FieldEndMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MonthlyFeeCents(); ok {
		_spec.SetField(pricetier.FieldMonthlyFeeCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthlyFeeCents(); ok {
		_spec.AddField(pricetier.FieldMonthlyFeeCents, field.TypeInt, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricetier.PlanTable,
			Columns: []string{pricetier.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricetier.PlanTable,
			Columns: []string{pricetier.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PriceTier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricetier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
