// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/pricetier"
	"github.com/rs/xid"
)

// PriceTier is the model entity for the PriceTier schema.
type PriceTier struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// StartMonth holds the value of the "start_month" field.
	StartMonth int `json:"start_month,omitempty"`
	// EndMonth holds the value of the "end_month" field.
	EndMonth int `json:"end_month,omitempty"`
	// MonthlyFeeCents holds the value of the "monthly_fee_cents" field.
	MonthlyFeeCents int `json:"monthly_fee_cents,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceTierQuery when eager-loading is set.
	Edges            PriceTierEdges `json:"edges"`
	plan_price_tiers *xid.ID
	selectValues     sql.SelectValues
}

// PriceTierEdges holds the relations/edges for other nodes in the graph.
type PriceTierEdges struct {
	// Plan holds the value of the plan edge.
	Plan *Plan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceTierEdges) PlanOrErr() (*Plan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PriceTier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricetier.FieldStartMonth, pricetier.FieldEndMonth, pricetier.FieldMonthlyFeeCents:
			values[i] = new(sql.NullInt64)
		case pricetier.FieldID:
			values[i] = new(xid.ID)
		case pricetier.ForeignKeys[0]: // plan_price_tiers
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PriceTier fields.
func (_m *PriceTier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricetier.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pricetier.FieldStartMonth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_month", values[i])
			} else if value.Valid {
				_m.StartMonth = int(value.Int64)
			}
		case pricetier.FieldEndMonth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_month", values[i])
			} else if value.Valid {
				_m.EndMonth = int(value.Int64)
			}
		case pricetier.FieldMonthlyFeeCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_fee_cents", values[i])
			} else if value.Valid {
				_m.MonthlyFeeCents = int(value.Int64)
			}
		case pricetier.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field plan_price_tiers", values[i])
			} else if value.Valid {
				_m.plan_price_tiers = new(xid.ID)
				*_m.plan_price_tiers = *value.S.(*xid.ID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PriceTier.
// This includes values selected through modifiers, order, etc.
func (_m *PriceTier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the PriceTier entity.
func (_m *PriceTier) QueryPlan() *PlanQuery {
	return NewPriceTierClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this PriceTier.
// Note that you need to call PriceTier.Unwrap() before calling this method if this PriceTier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PriceTier) Update() *PriceTierUpdateOne {
	return NewPriceTierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PriceTier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PriceTier) Unwrap() *PriceTier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PriceTier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PriceTier) String() string {
	var builder strings.Builder
	builder.WriteString("PriceTier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("start_month=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartMonth))
	builder.WriteString(", ")
	builder.WriteString("end_month=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndMonth))
	builder.WriteString(", ")
	builder.WriteString("monthly_fee_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyFeeCents))
	builder.WriteByte(')')
	return builder.String()
}

// PriceTiers is a parsable slice of PriceTier.
type PriceTiers []*PriceTier
