// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/pricetier"
	"github.com/rs/xid"
)

// PriceTierCreate is the builder for creating a PriceTier entity.
type PriceTierCreate struct {
	config
	mutation *PriceTierMutation
	hooks    []Hook
}

// SetStartMonth sets the "start_month" field.
func (_c *PriceTierCreate) SetStartMonth(v int) *PriceTierCreate {
	_c.mutation.SetStartMonth(v)
	return _c
}

// SetEndMonth sets the "end_month" field.
func (_c *PriceTierCreate) SetEndMonth(v int) *PriceTierCreate {
	_c.mutation.SetEndMonth(v)
	return _c
}

// SetMonthlyFeeCents sets the "monthly_fee_cents" field.
func (_c *PriceTierCreate) SetMonthlyFeeCents(v int) *PriceTierCreate {
	_c.mutation.SetMonthlyFeeCents(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PriceTierCreate) SetID(v xid.ID) *PriceTierCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PriceTierCreate) SetNillableID(v *xid.ID) *PriceTierCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_c *PriceTierCreate) SetPlanID(id xid.ID) *PriceTierCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *PriceTierCreate) SetPlan(v *Plan) *PriceTierCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the PriceTierMutation object of the builder.
func (_c *PriceTierCreate) Mutation() *PriceTierMutation {
	return _c.mutation
}

// Save creates the PriceTier in the database.
func (_c *PriceTierCreate) Save(ctx context.Context) (*PriceTier, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PriceTierCreate) SaveX(ctx context.Context) *PriceTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceTierCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceTierCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PriceTierCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := pricetier.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PriceTierCreate) check() error {
	if _, ok := _c.mutation.StartMonth(); !ok {
		return &ValidationError{Name: "start_month", err: errors.New(`ent: missing required field "PriceTier.start_month"`)}
	}
	if _, ok := _c.mutation.EndMonth(); !ok {
		return &ValidationError{Name: "end_month", err: errors.New(`ent: missing required field "PriceTier.end_month"`)}
	}
	if _, ok := _c.mutation.MonthlyFeeCents(); !ok {
		return &ValidationError{Name: "monthly_fee_cents", err: errors.New(`ent: missing required field "PriceTier.monthly_fee_cents"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "PriceTier.plan"`)}
	}
	return nil
}

func (_c *PriceTierCreate) sqlSave(ctx context.Context) (*PriceTier, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PriceTierCreate) createSpec() (*PriceTier, *sqlgraph.CreateSpec) {
	var (
		_node = &PriceTier{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricetier.Table, sqlgraph.NewFieldSpec(pricetier.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.StartMonth(); ok {
		_spec.SetField(pricetier.FieldStartMonth, field.TypeInt, value)
		_node.StartMonth = value
	}
	if value, ok := _c.mutation.EndMonth(); ok {
		_spec.SetField(pricetier.FieldEndMonth, field.TypeInt, value)
		_node.EndMonth = value
	}
	if value, ok := _c.mutation.MonthlyFeeCents(); ok {
		_spec.SetField(pricetier.FieldMonthlyFeeCents, field.TypeInt, value)
		_node.MonthlyFeeCents = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricetier.PlanTable,
			Columns: []string{pricetier.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.plan_price_tiers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PriceTierCreateBulk is the builder for creating many PriceTier entities in bulk.
type PriceTierCreateBulk struct {
	config
	err      error
	builders []*PriceTierCreate
}

// Save creates the PriceTier entities in the database.
func (_c *PriceTierCreateBulk) Save(ctx context.Context) ([]*PriceTier, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PriceTier, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PriceTierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PriceTierCreateBulk) SaveX(ctx context.Context) []*PriceTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceTierCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceTierCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
