// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/deicod/tarife/ent/promo"
	"github.com/rs/xid"
)

// PromoUpdate is the builder for updating Promo entities.
type PromoUpdate struct {
	config
	hooks     []Hook
	mutation  *PromoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PromoUpdate builder.
func (_u *PromoUpdate) Where(ps ...predicate.Promo) *PromoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *PromoUpdate) SetDescription(v string) *PromoUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableDescription(v *string) *PromoUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDiscountCents sets the "discount_cents" field.
func (_u *PromoUpdate) SetDiscountCents(v int) *PromoUpdate {
	_u.mutation.ResetDiscountCents()
	_u.mutation.SetDiscountCents(v)
	return _u
}

// SetNillableDiscountCents sets the "discount_cents" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableDiscountCents(v *int) *PromoUpdate {
	if v != nil {
		_u.SetDiscountCents(*v)
	}
	return _u
}

// AddDiscountCents adds value to the "discount_cents" field.
func (_u *PromoUpdate) AddDiscountCents(v int) *PromoUpdate {
	_u.mutation.AddDiscountCents(v)
	return _u
}

// SetMonthsApplies sets the "months_applies" field.
func (_u *PromoUpdate) SetMonthsApplies(v int) *PromoUpdate {
	_u.mutation.ResetMonthsApplies()
	_u.mutation.SetMonthsApplies(v)
	return _u
}

// SetNillableMonthsApplies sets the "months_applies" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableMonthsApplies(v *int) *PromoUpdate {
	if v != nil {
		_u.SetMonthsApplies(*v)
	}
	return _u
}

// AddMonthsApplies adds value to the "months_applies" field.
func (_u *PromoUpdate) AddMonthsApplies(v int) *PromoUpdate {
	_u.mutation.AddMonthsApplies(v)
	return _u
}

// ClearMonthsApplies clears the value of the "months_applies" field.
func (_u *PromoUpdate) ClearMonthsApplies() *PromoUpdate {
	_u.mutation.ClearMonthsApplies()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *PromoUpdate) SetStartsAt(v time.Time) *PromoUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableStartsAt(v *time.Time) *PromoUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *PromoUpdate) ClearStartsAt() *PromoUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *PromoUpdate) SetEndsAt(v time.Time) *PromoUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableEndsAt(v *time.Time) *PromoUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *PromoUpdate) ClearEndsAt() *PromoUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *PromoUpdate) SetConditions(v string) *PromoUpdate {
	_u.mutation.SetConditions(v)
	return _u
}

// SetNillableConditions sets the "conditions" field if the given value is not nil.
func (_u *PromoUpdate) SetNillableConditions(v *string) *PromoUpdate {
	if v != nil {
		_u.SetConditions(*v)
	}
	return _u
}

// ClearConditions clears the value of the "conditions" field.
func (_u *PromoUpdate) ClearConditions() *PromoUpdate {
	_u.mutation.ClearConditions()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *PromoUpdate) SetPlanID(id xid.ID) *PromoUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *PromoUpdate) SetPlan(v *Plan) *PromoUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PromoMutation object of the builder.
func (_u *PromoUpdate) Mutation() *PromoMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *PromoUpdate) ClearPlan() *PromoUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoUpdate) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Promo.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PromoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PromoUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PromoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promo.Table, promo.Columns, sqlgraph.NewFieldSpec(promo.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promo.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountCents(); ok {
		_spec.SetField(promo.FieldDiscountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscountCents(); ok {
		_spec.AddField(promo.FieldDiscountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MonthsApplies(); ok {
		_spec.SetField(promo.FieldMonthsApplies, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthsApplies(); ok {
		_spec.AddField(promo.FieldMonthsApplies, field.TypeInt, value)
	}
	if _u.mutation.MonthsAppliesCleared() {
		_spec.ClearField(promo.FieldMonthsApplies, field.TypeInt)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(promo.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(promo.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(promo.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(promo.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(promo.FieldConditions, field.TypeString, value)
	}
	if _u.mutation.ConditionsCleared() {
		_spec.ClearField(promo.FieldConditions, field.TypeString)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promo.PlanTable,
			Columns: []string{promo.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promo.PlanTable,
			Columns: []string{promo.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromoUpdateOne is the builder for updating a single Promo entity.
type PromoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PromoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDescription sets the "description" field.
func (_u *PromoUpdateOne) SetDescription(v string) *PromoUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableDescription(v *string) *PromoUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDiscountCents sets the "discount_cents" field.
func (_u *PromoUpdateOne) SetDiscountCents(v int) *PromoUpdateOne {
	_u.mutation.ResetDiscountCents()
	_u.mutation.SetDiscountCents(v)
	return _u
}

// SetNillableDiscountCents sets the "discount_cents" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableDiscountCents(v *int) *PromoUpdateOne {
	if v != nil {
		_u.SetDiscountCents(*v)
	}
	return _u
}

// AddDiscountCents adds value to the "discount_cents" field.
func (_u *PromoUpdateOne) AddDiscountCents(v int) *PromoUpdateOne {
	_u.mutation.AddDiscountCents(v)
	return _u
}

// SetMonthsApplies sets the "months_applies" field.
func (_u *PromoUpdateOne) SetMonthsApplies(v int) *PromoUpdateOne {
	_u.mutation.ResetMonthsApplies()
	_u.mutation.SetMonthsApplies(v)
	return _u
}

// SetNillableMonthsApplies sets the "months_applies" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableMonthsApplies(v *int) *PromoUpdateOne {
	if v != nil {
		_u.SetMonthsApplies(*v)
	}
	return _u
}

// AddMonthsApplies adds value to the "months_applies" field.
func (_u *PromoUpdateOne) AddMonthsApplies(v int) *PromoUpdateOne {
	_u.mutation.AddMonthsApplies(v)
	return _u
}

// ClearMonthsApplies clears the value of the "months_applies" field.
func (_u *PromoUpdateOne) ClearMonthsApplies() *PromoUpdateOne {
	_u.mutation.ClearMonthsApplies()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *PromoUpdateOne) SetStartsAt(v time.Time) *PromoUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableStartsAt(v *time.Time) *PromoUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *PromoUpdateOne) ClearStartsAt() *PromoUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *PromoUpdateOne) SetEndsAt(v time.Time) *PromoUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableEndsAt(v *time.Time) *PromoUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *PromoUpdateOne) ClearEndsAt() *PromoUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetConditions sets the "conditions" field.
func (_u *PromoUpdateOne) SetConditions(v string) *PromoUpdateOne {
	_u.mutation.SetConditions(v)
	return _u
}

// SetNillableConditions sets the "conditions" field if the given value is not nil.
func (_u *PromoUpdateOne) SetNillableConditions(v *string) *PromoUpdateOne {
	if v != nil {
		_u.SetConditions(*v)
	}
	return _u
}

// ClearConditions clears the value of the "conditions" field.
func (_u *PromoUpdateOne) ClearConditions() *PromoUpdateOne {
	_u.mutation.ClearConditions()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *PromoUpdateOne) SetPlanID(id xid.ID) *PromoUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *PromoUpdateOne) SetPlan(v *Plan) *PromoUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PromoMutation object of the builder.
func (_u *PromoUpdateOne) Mutation() *PromoMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *PromoUpdateOne) ClearPlan() *PromoUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the PromoUpdate builder.
func (_u *PromoUpdateOne) Where(ps ...predicate.Promo) *PromoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromoUpdateOne) Select(field string, fields ...string) *PromoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Promo entity.
func (_u *PromoUpdateOne) Save(ctx context.Context) (*Promo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoUpdateOne) SaveX(ctx context.Context) *Promo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoUpdateOne) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Promo.plan"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PromoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PromoUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PromoUpdateOne) sqlSave(ctx context.Context) (_node *Promo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promo.Table, promo.Columns, sqlgraph.NewFieldSpec(promo.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Promo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promo.FieldID)
		for _, f := range fields {
			if !promo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promo.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountCents(); ok {
		_spec.SetField(promo.FieldDiscountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscountCents(); ok {
		_spec.AddField(promo.FieldDiscountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MonthsApplies(); ok {
		_spec.SetField(promo.FieldMonthsApplies, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonthsApplies(); ok {
		_spec.AddField(promo.FieldMonthsApplies, field.TypeInt, value)
	}
	if _u.mutation.MonthsAppliesCleared() {
		_spec.ClearField(promo.FieldMonthsApplies, field.TypeInt)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(promo.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(promo.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(promo.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(promo.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Conditions(); ok {
		_spec.SetField(promo.FieldConditions, field.TypeString, value)
	}
	if _u.mutation.ConditionsCleared() {
		_spec.ClearField(promo.FieldConditions, field.TypeString)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promo.PlanTable,
			Columns: []string{promo.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promo.PlanTable,
			Columns: []string{promo.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Promo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
