// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/promo"
	"github.com/rs/xid"
)

// PromoCreate is the builder for creating a Promo entity.
type PromoCreate struct {
	config
	mutation *PromoMutation
	hooks    []Hook
}

// SetDescription sets the "description" field.
func (_c *PromoCreate) SetDescription(v string) *PromoCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetDiscountCents sets the "discount_cents" field.
func (_c *PromoCreate) SetDiscountCents(v int) *PromoCreate {
	_c.mutation.SetDiscountCents(v)
	return _c
}

// SetMonthsApplies sets the "months_applies" field.
func (_c *PromoCreate) SetMonthsApplies(v int) *PromoCreate {
	_c.mutation.SetMonthsApplies(v)
	return _c
}

// SetNillableMonthsApplies sets the "months_applies" field if the given value is not nil.
func (_c *PromoCreate) SetNillableMonthsApplies(v *int) *PromoCreate {
	if v != nil {
		_c.SetMonthsApplies(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *PromoCreate) SetStartsAt(v time.Time) *PromoCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *PromoCreate) SetNillableStartsAt(v *time.Time) *PromoCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *PromoCreate) SetEndsAt(v time.Time) *PromoCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *PromoCreate) SetNillableEndsAt(v *time.Time) *PromoCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *PromoCreate) SetConditions(v string) *PromoCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetNillableConditions sets the "conditions" field if the given value is not nil.
func (_c *PromoCreate) SetNillableConditions(v *string) *PromoCreate {
	if v != nil {
		_c.SetConditions(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromoCreate) SetID(v xid.ID) *PromoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromoCreate) SetNillableID(v *xid.ID) *PromoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_c *PromoCreate) SetPlanID(id xid.ID) *PromoCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *PromoCreate) SetPlan(v *Plan) *PromoCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the PromoMutation object of the builder.
func (_c *PromoCreate) Mutation() *PromoMutation {
	return _c.mutation
}

// Save creates the Promo in the database.
func (_c *PromoCreate) Save(ctx context.Context) (*Promo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromoCreate) SaveX(ctx context.Context) *Promo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromoCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := promo.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromoCreate) check() error {
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Promo.description"`)}
	}
	if _, ok := _c.mutation.DiscountCents(); !ok {
		return &ValidationError{Name: "discount_cents", err: errors.New(`ent: missing required field "Promo.discount_cents"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "Promo.plan"`)}
	}
	return nil
}

func (_c *PromoCreate) sqlSave(ctx context.Context) (*Promo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromoCreate) createSpec() (*Promo, *sqlgraph.CreateSpec) {
	var (
		_node = &Promo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promo.Table, sqlgraph.NewFieldSpec(promo.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(promo.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DiscountCents(); ok {
		_spec.SetField(promo.FieldDiscountCents, field.TypeInt, value)
		_node.DiscountCents = value
	}
	if value, ok := _c.mutation.MonthsApplies(); ok {
		_spec.SetField(promo.FieldMonthsApplies, field.TypeInt, value)
		_node.MonthsApplies = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(promo.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(promo.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(promo.FieldConditions, field.TypeString, value)
		_node.Conditions = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promo.PlanTable,
			Columns: []string{promo.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.plan_promos = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PromoCreateBulk is the builder for creating many Promo entities in bulk.
type PromoCreateBulk struct {
	config
	err      error
	builders []*PromoCreate
}

// Save creates the Promo entities in the database.
func (_c *PromoCreateBulk) Save(ctx context.Context) ([]*Promo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Promo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromoCreateBulk) SaveX(ctx context.Context) []*Promo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
