// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/tarife/ent/provider"
	"github.com/rs/xid"
)

// Provider is the model entity for the Provider schema.
type Provider struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Website holds the value of the "website" field.
	Website string `json:"website,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderQuery when eager-loading is set.
	Edges        ProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderEdges holds the relations/edges for other nodes in the graph.
type ProviderEdges struct {
	// Plans holds the value of the plans edge.
	Plans []*Plan `json:"plans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedPlans map[string][]*Plan
}

// PlansOrErr returns the Plans value or an error if the edge
// was not loaded in eager-loading.
func (e ProviderEdges) PlansOrErr() ([]*Plan, error) {
	if e.loadedTypes[0] {
		return e.Plans, nil
	}
	return nil, &NotLoadedError{edge: "plans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Provider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case provider.FieldName, provider.FieldWebsite:
			values[i] = new(sql.NullString)
		case provider.FieldID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Provider fields.
func (_m *Provider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case provider.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case provider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case provider.FieldWebsite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website", values[i])
			} else if value.Valid {
				_m.Website = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Provider.
// This includes values selected through modifiers, order, etc.
func (_m *Provider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlans queries the "plans" edge of the Provider entity.
func (_m *Provider) QueryPlans() *PlanQuery {
	return NewProviderClient(_m.config).QueryPlans(_m)
}

// Update returns a builder for updating this Provider.
// Note that you need to call Provider.Unwrap() before calling this method if this Provider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Provider) Update() *ProviderUpdateOne {
	return NewProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Provider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Provider) Unwrap() *Provider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Provider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Provider) String() string {
	var builder strings.Builder
	builder.WriteString("Provider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("website=")
	builder.WriteString(_m.Website)
	builder.WriteByte(')')
	return builder.String()
}

// NamedPlans returns the Plans named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Provider) NamedPlans(name string) ([]*Plan, error) {
	if _m.Edges.namedPlans == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPlans[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Provider) appendNamedPlans(name string, edges ...*Plan) {
	if _m.Edges.namedPlans == nil {
		_m.Edges.namedPlans = make(map[string][]*Plan)
	}
	if len(edges) == 0 {
		_m.Edges.namedPlans[name] = []*Plan{}
	} else {
		_m.Edges.namedPlans[name] = append(_m.Edges.namedPlans[name], edges...)
	}
}

// Providers is a parsable slice of Provider.
type Providers []*Provider
