// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/tarife/ent/plan"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/deicod/tarife/ent/provider"
	"github.com/rs/xid"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks     []Hook
	mutation  *ProviderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderUpdate) SetName(v string) *ProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableName(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWebsite sets the "website" field.
func (_u *ProviderUpdate) SetWebsite(v string) *ProviderUpdate {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableWebsite(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *ProviderUpdate) AddPlanIDs(ids ...xid.ID) *ProviderUpdate {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *ProviderUpdate) AddPlans(v ...*Plan) *ProviderUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdate) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *ProviderUpdate) ClearPlans() *ProviderUpdate {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *ProviderUpdate) RemovePlanIDs(ids ...xid.ID) *ProviderUpdate {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *ProviderUpdate) RemovePlans(v ...*Plan) *ProviderUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(provider.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProviderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *ProviderUpdateOne) SetName(v string) *ProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableName(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWebsite sets the "website" field.
func (_u *ProviderUpdateOne) SetWebsite(v string) *ProviderUpdateOne {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableWebsite(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *ProviderUpdateOne) AddPlanIDs(ids ...xid.ID) *ProviderUpdateOne {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *ProviderUpdateOne) AddPlans(v ...*Plan) *ProviderUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdateOne) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *ProviderUpdateOne) ClearPlans() *ProviderUpdateOne {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *ProviderUpdateOne) RemovePlanIDs(ids ...xid.ID) *ProviderUpdateOne {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *ProviderUpdateOne) RemovePlans(v ...*Plan) *ProviderUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Provider entity.
func (_u *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(provider.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.PlansTable,
			Columns: []string{provider.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Provider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
