// Code generated by ent, DO NOT EDIT.

package promo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/deicod/tarife/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldDescription, v))
}

// DiscountCents applies equality check predicate on the "discount_cents" field. It's identical to DiscountCentsEQ.
func DiscountCents(v int) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldDiscountCents, v))
}

// MonthsApplies applies equality check predicate on the "months_applies" field. It's identical to MonthsAppliesEQ.
func MonthsApplies(v int) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldMonthsApplies, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldEndsAt, v))
}

// Conditions applies equality check predicate on the "conditions" field. It's identical to ConditionsEQ.
func Conditions(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldConditions, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Promo {
	return predicate.Promo(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Promo {
	return predicate.Promo(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Promo {
	return predicate.Promo(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Promo {
	return predicate.Promo(sql.FieldContainsFold(FieldDescription, v))
}

// DiscountCentsEQ applies the EQ predicate on the "discount_cents" field.
func DiscountCentsEQ(v int) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldDiscountCents, v))
}

// DiscountCentsNEQ applies the NEQ predicate on the "discount_cents" field.
func DiscountCentsNEQ(v int) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldDiscountCents, v))
}

// DiscountCentsIn applies the In predicate on the "discount_cents" field.
func DiscountCentsIn(vs ...int) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldDiscountCents, vs...))
}

// DiscountCentsNotIn applies the NotIn predicate on the "discount_cents" field.
func DiscountCentsNotIn(vs ...int) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldDiscountCents, vs...))
}

// DiscountCentsGT applies the GT predicate on the "discount_cents" field.
func DiscountCentsGT(v int) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldDiscountCents, v))
}

// DiscountCentsGTE applies the GTE predicate on the "discount_cents" field.
func DiscountCentsGTE(v int) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldDiscountCents, v))
}

// DiscountCentsLT applies the LT predicate on the "discount_cents" field.
func DiscountCentsLT(v int) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldDiscountCents, v))
}

// DiscountCentsLTE applies the LTE predicate on the "discount_cents" field.
func DiscountCentsLTE(v int) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldDiscountCents, v))
}

// MonthsAppliesEQ applies the EQ predicate on the "months_applies" field.
func MonthsAppliesEQ(v int) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldMonthsApplies, v))
}

// MonthsAppliesNEQ applies the NEQ predicate on the "months_applies" field.
func MonthsAppliesNEQ(v int) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldMonthsApplies, v))
}

// MonthsAppliesIn applies the In predicate on the "months_applies" field.
func MonthsAppliesIn(vs ...int) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldMonthsApplies, vs...))
}

// MonthsAppliesNotIn applies the NotIn predicate on the "months_applies" field.
func MonthsAppliesNotIn(vs ...int) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldMonthsApplies, vs...))
}

// MonthsAppliesGT applies the GT predicate on the "months_applies" field.
func MonthsAppliesGT(v int) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldMonthsApplies, v))
}

// MonthsAppliesGTE applies the GTE predicate on the "months_applies" field.
func MonthsAppliesGTE(v int) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldMonthsApplies, v))
}

// MonthsAppliesLT applies the LT predicate on the "months_applies" field.
func MonthsAppliesLT(v int) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldMonthsApplies, v))
}

// MonthsAppliesLTE applies the LTE predicate on the "months_applies" field.
func MonthsAppliesLTE(v int) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldMonthsApplies, v))
}

// MonthsAppliesIsNil applies the IsNil predicate on the "months_applies" field.
func MonthsAppliesIsNil() predicate.Promo {
	return predicate.Promo(sql.FieldIsNull(FieldMonthsApplies))
}

// MonthsAppliesNotNil applies the NotNil predicate on the "months_applies" field.
func MonthsAppliesNotNil() predicate.Promo {
	return predicate.Promo(sql.FieldNotNull(FieldMonthsApplies))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldStartsAt, v))
}

// StartsAtIsNil applies the IsNil predicate on the "starts_at" field.
func StartsAtIsNil() predicate.Promo {
	return predicate.Promo(sql.FieldIsNull(FieldStartsAt))
}

// StartsAtNotNil applies the NotNil predicate on the "starts_at" field.
func StartsAtNotNil() predicate.Promo {
	return predicate.Promo(sql.FieldNotNull(FieldStartsAt))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldEndsAt, v))
}

// EndsAtIsNil applies the IsNil predicate on the "ends_at" field.
func EndsAtIsNil() predicate.Promo {
	return predicate.Promo(sql.FieldIsNull(FieldEndsAt))
}

// EndsAtNotNil applies the NotNil predicate on the "ends_at" field.
func EndsAtNotNil() predicate.Promo {
	return predicate.Promo(sql.FieldNotNull(FieldEndsAt))
}

// ConditionsEQ applies the EQ predicate on the "conditions" field.
func ConditionsEQ(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEQ(FieldConditions, v))
}

// ConditionsNEQ applies the NEQ predicate on the "conditions" field.
func ConditionsNEQ(v string) predicate.Promo {
	return predicate.Promo(sql.FieldNEQ(FieldConditions, v))
}

// ConditionsIn applies the In predicate on the "conditions" field.
func ConditionsIn(vs ...string) predicate.Promo {
	return predicate.Promo(sql.FieldIn(FieldConditions, vs...))
}

// ConditionsNotIn applies the NotIn predicate on the "conditions" field.
func ConditionsNotIn(vs ...string) predicate.Promo {
	return predicate.Promo(sql.FieldNotIn(FieldConditions, vs...))
}

// ConditionsGT applies the GT predicate on the "conditions" field.
func ConditionsGT(v string) predicate.Promo {
	return predicate.Promo(sql.FieldGT(FieldConditions, v))
}

// ConditionsGTE applies the GTE predicate on the "conditions" field.
func ConditionsGTE(v string) predicate.Promo {
	return predicate.Promo(sql.FieldGTE(FieldConditions, v))
}

// ConditionsLT applies the LT predicate on the "conditions" field.
func ConditionsLT(v string) predicate.Promo {
	return predicate.Promo(sql.FieldLT(FieldConditions, v))
}

// ConditionsLTE applies the LTE predicate on the "conditions" field.
func ConditionsLTE(v string) predicate.Promo {
	return predicate.Promo(sql.FieldLTE(FieldConditions, v))
}

// ConditionsContains applies the Contains predicate on the "conditions" field.
func ConditionsContains(v string) predicate.Promo {
	return predicate.Promo(sql.FieldContains(FieldConditions, v))
}

// ConditionsHasPrefix applies the HasPrefix predicate on the "conditions" field.
func ConditionsHasPrefix(v string) predicate.Promo {
	return predicate.Promo(sql.FieldHasPrefix(FieldConditions, v))
}

// ConditionsHasSuffix applies the HasSuffix predicate on the "conditions" field.
func ConditionsHasSuffix(v string) predicate.Promo {
	return predicate.Promo(sql.FieldHasSuffix(FieldConditions, v))
}

// ConditionsIsNil applies the IsNil predicate on the "conditions" field.
func ConditionsIsNil() predicate.Promo {
	return predicate.Promo(sql.FieldIsNull(FieldConditions))
}

// ConditionsNotNil applies the NotNil predicate on the "conditions" field.
func ConditionsNotNil() predicate.Promo {
	return predicate.Promo(sql.FieldNotNull(FieldConditions))
}

// ConditionsEqualFold applies the EqualFold predicate on the "conditions" field.
func ConditionsEqualFold(v string) predicate.Promo {
	return predicate.Promo(sql.FieldEqualFold(FieldConditions, v))
}

// ConditionsContainsFold applies the ContainsFold predicate on the "conditions" field.
func ConditionsContainsFold(v string) predicate.Promo {
	return predicate.Promo(sql.FieldContainsFold(FieldConditions, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.Promo {
	return predicate.Promo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.Plan) predicate.Promo {
	return predicate.Promo(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Promo) predicate.Promo {
	return predicate.Promo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Promo) predicate.Promo {
	return predicate.Promo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Promo) predicate.Promo {
	return predicate.Promo(sql.NotPredicates(p))
}
