// Code generated by ent, DO NOT EDIT.

package plan

import (
	"fmt"
	"io"
	"strconv"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the plan type in the database.
	Label = "plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTechnology holds the string denoting the technology field in the database.
	FieldTechnology = "technology"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMinTermMonths holds the string denoting the min_term_months field in the database.
	FieldMinTermMonths = "min_term_months"
	// FieldCancelNoticeDays holds the string denoting the cancel_notice_days field in the database.
	FieldCancelNoticeDays = "cancel_notice_days"
	// FieldValidFrom holds the string denoting the valid_from field in the database.
	FieldValidFrom = "valid_from"
	// FieldValidTo holds the string denoting the valid_to field in the database.
	FieldValidTo = "valid_to"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldVersionTag holds the string denoting the version_tag field in the database.
	FieldVersionTag = "version_tag"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeBandwidth holds the string denoting the bandwidth edge name in mutations.
	EdgeBandwidth = "bandwidth"
	// EdgePriceTiers holds the string denoting the price_tiers edge name in mutations.
	EdgePriceTiers = "price_tiers"
	// EdgeOneTimeFees holds the string denoting the one_time_fees edge name in mutations.
	EdgeOneTimeFees = "one_time_fees"
	// EdgePromos holds the string denoting the promos edge name in mutations.
	EdgePromos = "promos"
	// EdgeAddon holds the string denoting the addon edge name in mutations.
	EdgeAddon = "addon"
	// Table holds the table name of the plan in the database.
	Table = "plans"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "plans"
	// ProviderInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProviderInverseTable = "providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_plans"
	// BandwidthTable is the table that holds the bandwidth relation/edge.
	BandwidthTable = "bandwidths"
	// BandwidthInverseTable is the table name for the Bandwidth entity.
	// It exists in this package in order to avoid circular dependency with the "bandwidth" package.
	BandwidthInverseTable = "bandwidths"
	// BandwidthColumn is the table column denoting the bandwidth relation/edge.
	BandwidthColumn = "plan_bandwidth"
	// PriceTiersTable is the table that holds the price_tiers relation/edge.
	PriceTiersTable = "price_tiers"
	// PriceTiersInverseTable is the table name for the PriceTier entity.
	// It exists in this package in order to avoid circular dependency with the "pricetier" package.
	PriceTiersInverseTable = "price_tiers"
	// PriceTiersColumn is the table column denoting the price_tiers relation/edge.
	PriceTiersColumn = "plan_price_tiers"
	// OneTimeFeesTable is the table that holds the one_time_fees relation/edge.
	OneTimeFeesTable = "one_time_fees"
	// OneTimeFeesInverseTable is the table name for the OneTimeFee entity.
	// It exists in this package in order to avoid circular dependency with the "onetimefee" package.
	OneTimeFeesInverseTable = "one_time_fees"
	// OneTimeFeesColumn is the table column denoting the one_time_fees relation/edge.
	OneTimeFeesColumn = "plan_one_time_fees"
	// PromosTable is the table that holds the promos relation/edge.
	PromosTable = "promos"
	// PromosInverseTable is the table name for the Promo entity.
	// It exists in this package in order to avoid circular dependency with the "promo" package.
	PromosInverseTable = "promos"
	// PromosColumn is the table column denoting the promos relation/edge.
	PromosColumn = "plan_promos"
	// AddonTable is the table that holds the addon relation/edge. The primary key declared below.
	AddonTable = "addon_plans"
	// AddonInverseTable is the table name for the Addon entity.
	// It exists in this package in order to avoid circular dependency with the "addon" package.
	AddonInverseTable = "addons"
)

// Columns holds all SQL columns for plan fields.
var Columns = []string{
	FieldID,
	FieldTechnology,
	FieldName,
	FieldDescription,
	FieldMinTermMonths,
	FieldCancelNoticeDays,
	FieldValidFrom,
	FieldValidTo,
	FieldSourceURL,
	FieldVersionTag,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "plans"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"provider_plans",
}

var (
	// AddonPrimaryKey and AddonColumn2 are the table columns denoting the
	// primary key for the addon relation (M2M).
	AddonPrimaryKey = []string{"addon_id", "plan_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMinTermMonths holds the default value on creation for the "min_term_months" field.
	DefaultMinTermMonths int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// Technology defines the type for the "technology" enum field.
type Technology string

// Technology values.
const (
	TechnologyFTTH   Technology = "FTTH"
	TechnologyDSL    Technology = "DSL"
	TechnologyCABLE  Technology = "CABLE"
	TechnologyMOBILE Technology = "MOBILE"
)

func (t Technology) String() string {
	return string(t)
}

// TechnologyValidator is a validator for the "technology" field enum values. It is called by the builders before save.
func TechnologyValidator(t Technology) error {
	switch t {
	case TechnologyFTTH, TechnologyDSL, TechnologyCABLE, TechnologyMOBILE:
		return nil
	default:
		return fmt.Errorf("plan: invalid enum value for technology field: %q", t)
	}
}

// OrderOption defines the ordering options for the Plan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTechnology orders the results by the technology field.
func ByTechnology(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechnology, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMinTermMonths orders the results by the min_term_months field.
func ByMinTermMonths(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinTermMonths, opts...).ToFunc()
}

// ByCancelNoticeDays orders the results by the cancel_notice_days field.
func ByCancelNoticeDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelNoticeDays, opts...).ToFunc()
}

// ByValidFrom orders the results by the valid_from field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByValidTo orders the results by the valid_to field.
func ByValidTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidTo, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByVersionTag orders the results by the version_tag field.
func ByVersionTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionTag, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByBandwidthField orders the results by bandwidth field.
func ByBandwidthField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBandwidthStep(), sql.OrderByField(field, opts...))
	}
}

// ByPriceTiersCount orders the results by price_tiers count.
func ByPriceTiersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPriceTiersStep(), opts...)
	}
}

// ByPriceTiers orders the results by price_tiers terms.
func ByPriceTiers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPriceTiersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOneTimeFeesCount orders the results by one_time_fees count.
func ByOneTimeFeesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOneTimeFeesStep(), opts...)
	}
}

// ByOneTimeFees orders the results by one_time_fees terms.
func ByOneTimeFees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOneTimeFeesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPromosCount orders the results by promos count.
func ByPromosCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPromosStep(), opts...)
	}
}

// ByPromos orders the results by promos terms.
func ByPromos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromosStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAddonCount orders the results by addon count.
func ByAddonCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAddonStep(), opts...)
	}
}

// ByAddon orders the results by addon terms.
func ByAddon(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAddonStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newBandwidthStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BandwidthInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BandwidthTable, BandwidthColumn),
	)
}
func newPriceTiersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PriceTiersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PriceTiersTable, PriceTiersColumn),
	)
}
func newOneTimeFeesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OneTimeFeesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OneTimeFeesTable, OneTimeFeesColumn),
	)
}
func newPromosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PromosTable, PromosColumn),
	)
}
func newAddonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AddonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, AddonTable, AddonPrimaryKey...),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Technology) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Technology) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Technology(str)
	if err := TechnologyValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Technology", str)
	}
	return nil
}
